@url = http://localhost:3000/api

# --- Usuarios (Auth) ---

# Registrar Usuario
POST {{url}}/auth/register
Content-Type: application/json

{
  "nombre": "Gino",
  "email": "gino@test.com",
  "contrasena": "password123"
}

###

# Login Usuario
# @name loginRequest
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "gino@test.com",
  "contrasena": "password123"
}
###
# captura el token de la respuesta del login
@token = {{loginRequest.response.body.token}} 


###
# --- Pacientes ---


# Obtener Todos los Pacientes
GET {{url}}/pacientes
# Aquí utilizamos el token #
Authorization: Bearer {{token}} 
###

# Obtener Paciente por ID
GET {{url}}/pacientes/1
Authorization: Bearer {{token}}

###

# Crear Paciente
POST {{url}}/pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Paciente",
  "apellido": "Prueba",
  "DNI": "98765432",
  "fecha_nacimiento": "1995-05-15",
  "obra_social": "OSDE"
}

###

# Actualizar Paciente
PUT {{url}}/pacientes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Paciente Actualizado",
  "apellido": "Prueba",
  "DNI": "98765432",
  "fecha_nacimiento": "1995-05-15",
  "obra_social": "PAMI"
}

###

# Borrar Paciente
DELETE {{url}}/pacientes/1
Authorization: Bearer {{token}}

###

# --- Médicos ---

# Obtener Todos los Médicos
GET {{url}}/medicos
Authorization: Bearer {{token}} 

###

# Obtener Médico por ID
GET {{url}}/medicos/1
Authorization: Bearer {{token}} 


###
# Crear Médico
POST {{url}}/medicos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Dr.",
  "apellido": "House",
  "especialidad": "Cancer",
  "matricula_profesional": "M00"
}


###

# Borrar Médico
DELETE {{url}}/medicos/1
Authorization: Bearer {{token}}

###

# --- Turnos ---

# Obtener Todos los Turnos
GET {{url}}/turnos
Authorization: Bearer {{token}} 

###

# Obtener Turno por ID
GET {{url}}/turnos/1
Authorization: Bearer {{token}}

###

# Crear Turno
POST {{url}}/turnos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "paciente_id": 1,
  "medico_id": 1,
  "fecha": "2025-11-20",
  "hora": "10:30:00",
  "estado": "pendiente",
  "observaciones": "Dolor de cabeza"
}

###

# Borrar Turno
DELETE {{url}}/turnos/1
Authorization: Bearer {{token}}